FROM openjdk:23
WORKDIR /app

COPY ./src/ ./src/

COPY ./libs/attempt2/*.jar ./libs/

RUN mkdir build && javac -cp "libs/*" -d build src/PlayerData.java src/SearchServer2S.java

EXPOSE 30000
CMD ["java", "-cp", "build:libs/*", "SearchServer2S"]