FROM openjdk:23
WORKDIR /app

# Copy source code and libraries
COPY ./src/ ./src/
COPY ./libs/*.jar ./libs/

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}

# Compile Java source with external dependencies
RUN mkdir build && javac -cp "libs/*" -d build src/SearchServer2S.java src/PlayerData.java
# Expose SearchServer port
EXPOSE 30000

# Run the compiled server with classpath for both classes and JARs
CMD ["java", "-cp", "build:libs/*:libs/attempt2/*", "SearchServer2S"]